version: '3.3'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    networks:
      - car_lookups_default
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    ports:
      - 5432:5432

secrets:
  postgres_password:
    file: ./docker_postgres_password


volumes:
  pgdata:


networks:
  car_lookups_default:
